# Generated by Django 5.0.6 on 2024-06-30 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='img',
            field=models.ImageField(default='defaultExercise.png', null=True, upload_to='exercise_pics'),
        ),
    ]
